-- Stable state IDs are saved in the shared player profile. Append new stages;
-- do not renumber existing states when adding the rest of the adventure.
local AnniversaryQuestConfig = {
	Name = "AnniversaryQuest",
	AdventureStateId = 2,
	ReturnPlaceId = 8481844229,
	SchoolBellSoundId = "rbxassetid://138704534210583",
	EnablePoliceClassroom = false, -- Re-enable Leo when the police chapter is ready.
	States = {
		ClassroomIntro = 1,
		YourFuture = 2,
		DoctorIntro = 2, -- Preserve the previously saved YourFuture checkpoint.
		DoctorTasks = 3,
		DoctorComplete = 4,
		PoliceClassroom = 5,
		PoliceReady = 6,
		ClassroomFinale = 6, -- Temporary route until the other roleplay chapters exist.
		QuestComplete = 7,
	},
	Objectives = {
		{
			Id = 1,
			Key = "ClassroomIntro",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Listen to your classmates' dreams",
			ResumeMarker = "Arrival",
			Cutscene = "ClassroomIntro",
		},
		{
			Id = 2,
			Key = "YourFuture",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Your first shift as a doctor",
			ResumeStage = "DoctorQuest",
			ResumeMarker = "Arrival",
			Cutscene = "DoctorIntro",
		},
		{
			Id = 3,
			Key = "DoctorTasks",
			Type = "Event",
			Goal = 6,
			Progress = 0,
			Description = "Complete the patient care board",
			ResumeStage = "DoctorQuest",
			ResumeMarker = "Arrival",
		},
		{
			Id = 4,
			Key = "DoctorComplete",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Doctor shift complete — the patient is stable",
			ResumeStage = "DoctorQuest",
			ResumeMarker = "Arrival",
		},
		{
			Id = 5,
			Key = "PoliceClassroom",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Listen to Leo's dream",
			ResumeStage = "ClassroomIntro",
			ResumeMarker = "Arrival",
			Cutscene = "PoliceClassroom",
		},
		{
			Id = 6,
			Key = "ClassroomFinale",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "What do you want to be?",
			ResumeStage = "ClassroomIntro",
			ResumeMarker = "Arrival",
			Cutscene = "ClassroomFinale",
		},
		{
			Id = 7,
			Key = "QuestComplete",
			Type = "Event",
			Goal = 1,
			Progress = 1,
			Description = "Quest complete! Class dismissed.",
			ResumeStage = "ClassroomIntro",
			ResumeMarker = "Arrival",
		},
	},
}

return AnniversaryQuestConfig
