-- Stable state IDs are saved in the shared player profile. Append new stages;
-- do not renumber existing states when adding the rest of the adventure.
local AnniversaryQuestConfig = {
	Name = "AnniversaryQuest",
	AdventureStateId = 2,
	ReturnPlaceId = 8481844229,
	CompletionBadgeId = 3360234962904323,
	SchoolBellSoundId = "rbxassetid://138704534210583",
	EnterDreamSoundId = "rbxassetid://89768647782835",
	ReturnToRealitySoundId = "rbxassetid://101519970536731",
	ClassroomMusicSoundId = "rbxassetid://1837383248",
	ClassroomMusicVolume = 0.12,
	EnablePoliceClassroom = true,
	States = {
		ClassroomIntro = 1,
		YourFuture = 2,
		DoctorIntro = 2, -- Preserve the previously saved YourFuture checkpoint.
		DoctorTasks = 3,
		DoctorComplete = 4,
		PoliceClassroom = 5,
		PoliceReady = 6,
		ClassroomFinale = 6,
		QuestComplete = 7,
		PoliceIntro = 8,
		PoliceSearch = 9,
		PoliceFingerprints = 10,
		PoliceMugshot = 11,
		PoliceOpenCell = 12,
		PoliceEscortCell = 13,
		PoliceCloseCell = 14,
		PoliceComplete = 15,
		FlightIntro = 16,
		FlightAnnouncement = 17,
		FlightSeatbelt = 18,
		FlightTakeoff = 19,
		FlightMeals = 20,
		FlightComplete = 21,
		FlightClassroom = 22,
	},
	Objectives = {
		{
			Id = 1,
			Key = "ClassroomIntro",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Listen to your classmates' dreams",
			ResumeMarker = "Arrival",
			Cutscene = "ClassroomIntro",
		},
		{
			Id = 2,
			Key = "YourFuture",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Your first shift as a doctor",
			ResumeStage = "DoctorQuest",
			ResumeMarker = "Arrival",
			Cutscene = "DoctorIntro",
		},
		{
			Id = 3,
			Key = "DoctorTasks",
			Type = "Event",
			Goal = 6,
			Progress = 0,
			Description = "Complete the patient care board",
			ResumeStage = "DoctorQuest",
			ResumeMarker = "Arrival",
		},
		{
			Id = 4,
			Key = "DoctorComplete",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Doctor shift complete — the patient is stable",
			ResumeStage = "DoctorQuest",
			ResumeMarker = "Arrival",
		},
		{
			Id = 5,
			Key = "PoliceClassroom",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Listen to Leo's dream",
			ResumeStage = "ClassroomIntro",
			ResumeMarker = "Arrival",
			Cutscene = "PoliceClassroom",
		},
		{
			Id = 6,
			Key = "ClassroomFinale",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "What do you want to be?",
			ResumeStage = "ClassroomIntro",
			ResumeMarker = "Arrival",
			Cutscene = "ClassroomFinale",
		},
		{
			Id = 7,
			Key = "QuestComplete",
			Type = "Event",
			Goal = 1,
			Progress = 1,
			Description = "Quest complete! Class dismissed.",
			ResumeStage = "ClassroomIntro",
			ResumeMarker = "Arrival",
		},
		{
			Id = 8,
			Key = "PoliceIntro",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Join Leo for your police shift",
			ResumeStage = "PoliceQuest",
			ResumeMarker = "Arrival",
			Cutscene = "PoliceIntro",
		},
		{
			Id = 9,
			Key = "PoliceSearch",
			Type = "Event",
			Goal = 6,
			Progress = 0,
			Description = "Search the suspect and confiscate their belongings",
			ResumeStage = "PoliceQuest",
			ResumeMarker = "SearchArrival",
		},
		{
			Id = 10,
			Key = "PoliceFingerprints",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Scan the suspect's fingerprints",
			ResumeStage = "PoliceQuest",
			ResumeMarker = "FingerprintArrival",
		},
		{
			Id = 11,
			Key = "PoliceMugshot",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Take the suspect's mugshot",
			ResumeStage = "PoliceQuest",
			ResumeMarker = "MugshotArrival",
		},
		{
			Id = 12,
			Key = "PoliceOpenCell",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Open the holding cell",
			ResumeStage = "PoliceQuest",
			ResumeMarker = "CellArrival",
		},
		{
			Id = 13,
			Key = "PoliceEscortCell",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Escort the suspect into the cell",
			ResumeStage = "PoliceQuest",
			ResumeMarker = "CellArrival",
		},
		{
			Id = 14,
			Key = "PoliceCloseCell",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Close the cell door to finish booking",
			ResumeStage = "PoliceQuest",
			ResumeMarker = "CellArrival",
		},
		{
			Id = 15,
			Key = "PoliceComplete",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Police shift complete — booking finished",
			ResumeStage = "PoliceQuest",
			ResumeMarker = "CellArrival",
		},
		{
			Id = 16,
			Key = "FlightIntro",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Welcome aboard your cabin crew shift",
			ResumeStage = "FlightQuest",
			ResumeMarker = "Arrival",
			Cutscene = "FlightIntro",
		},
		{
			Id = 17,
			Key = "FlightAnnouncement",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Start the safety announcement at the galley",
			ResumeStage = "FlightQuest",
			ResumeMarker = "Arrival",
		},
		{
			Id = 18,
			Key = "FlightSeatbelt",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Help Ben fasten his seatbelt",
			ResumeStage = "FlightQuest",
			ResumeMarker = "Arrival",
		},
		{
			Id = 19,
			Key = "FlightTakeoff",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Take your hostess seat for takeoff",
			ResumeStage = "FlightQuest",
			ResumeMarker = "Arrival",
		},
		{
			Id = 20,
			Key = "FlightMeals",
			Type = "Event",
			Goal = 6,
			Progress = 0,
			Description = "Deliver the requested meals to six passengers",
			ResumeStage = "FlightQuest",
			ResumeMarker = "Arrival",
		},
		{
			Id = 21,
			Key = "FlightComplete",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Cabin service complete — enjoy the flight",
			ResumeStage = "FlightQuest",
			ResumeMarker = "Arrival",
		},
		{
			Id = 22,
			Key = "FlightClassroom",
			Type = "Event",
			Goal = 1,
			Progress = 0,
			Description = "Listen to Amira's dream",
			ResumeStage = "ClassroomIntro",
			ResumeMarker = "Arrival",
			Cutscene = "FlightClassroom",
		},
	},
}

return AnniversaryQuestConfig
